=== ga4gh-beacon/beacon-v2/framework/json/responses/sections/beaconResponseMeta.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "description": "Information about the response that could be relevant for the Beacon client in order to interpret the results.",
    "properties": {
        "apiVersion": {
            "$ref": "../../common/beaconCommonComponents.json#/definitions/ApiVersion"
        },
        "beaconId": {
            "$ref": "../../common/beaconCommonComponents.json#/definitions/BeaconId"
        },
        "receivedRequestSummary": {
            "$ref": "./beaconReceivedRequestSummary.json"
        },
        "returnedGranularity": {
            "$ref": "../../common/beaconCommonComponents.json#/definitions/Granularity",
            "description": "Granularity of the Beacon response which may differ from the requested one. For details see the prototype definition."
        },
        "returnedSchemas": {
            "$ref": "../../common/beaconCommonComponents.json#/definitions/ListOfSchemas",
            "description": "The `returnedSchemas` parameter indicates that the request has been interpreted for the indicated entry type. This helps to disambiguate between negative responses due to e.g. no hit on a well understood request and failures to interpret or answer the request due to a missing entry type. "
        },
        "testMode": {
            "$ref": "../../common/beaconCommonComponents.json#/definitions/TestMode"
        }
    },
    "required": [
        "beaconId",
        "apiVersion",
        "returnedSchemas",
        "returnedGranularity",
        "receivedRequestSummary"
    ],
    "type": "object"
}

=== ga4gh-beacon/beacon-v2/framework/json/responses/examples-sections/beaconResponseMeta-example.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "apiVersion": "v2.0",
    "beaconId": "org.example.beacon.v2",
    "receivedRequestSummary": {
        "apiVersion": "2.0",
        "pagination": {
            "limit": 10,
            "skip": 0
        },
        "requestedGranularity": "count",
        "requestedSchemas": [
            {
                "entryType": "EntryTypeB",
                "schema": "entry-typeB-schema-v1.0"
            }
        ],
        "testMode": true
    },
    "returnedGranularity": "count",
    "returnedSchemas": [
        {
            "entryType": "EntryTypeB",
            "schema": "entry-typeB-schema-v1.0"
        }
    ]
}
