=== ga4gh-beacon/beacon-v2/models/json/beacon-v2-default-model/individuals/defaultSchema.json
{
    "$comment": "version: ga4gh-beacon-individual-v2.0.0",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "additionalProperties": true,
    "description": "Schema for an individual entry.",
    "properties": {
        "diseases": {
            "description": "List of disease(s) been diagnosed to the individual, defined by disease ontology ID(s), age of onset, stage and the presence of family history.",
            "items": {
                "$ref": "../common/disease.json"
            },
            "type": "array"
        },
        "ethnicity": {
            "$ref": "../common/commonDefinitions.json#/$defs/Ethnicity",
            "description": "Ethnic background of the individual. Value from NCIT Race (NCIT:C17049) ontology term descendants, e.g. NCIT:C126531 (Latin American). A geographic ancestral origin category that is assigned to a population group based mainly on physical characteristics that are thought to be distinct and inherent. [ NCI ] "
        },
        "exposures": {
            "items": {
                "$ref": "../common/exposure.json"
            },
            "type": "array"
        },
        "geographicOrigin": {
            "$ref": "../common/commonDefinitions.json#/$defs/GeographicLocation",
            "description": "Individual's country or region of origin (birthplace or residence place regardless of ethnic origin). Value from GAZ Geographic Location ontology (GAZ:00000448), e.g. GAZ:00002459 (United States of America)."
        },
        "id": {
            "description": "Individual identifier (internal ID).",
            "example": "P0001",
            "type": "string"
        },
        "info": {
            "$ref": "../common/info.json"
        },
        "interventionsOrProcedures": {
            "items": {
                "$ref": "../common/procedure.json"
            },
            "type": "array"
        },
        "karyotypicSex": {
            "$ref": "../common/commonDefinitions.json#/$defs/KaryotypicSex",
            "description": "The chromosomal sex of an individual represented from a selection of options."
        },
        "measures": {
            "items": {
                "$ref": "../common/measurement.json"
            },
            "type": "array"
        },
        "pedigrees": {
            "items": {
                "$ref": "../common/pedigree.json"
            },
            "type": "array"
        },
        "phenotypicFeatures": {
            "items": {
                "$ref": "../common/phenotypicFeature.json"
            },
            "type": "array"
        },
        "sex": {
            "$ref": "../common/commonDefinitions.json#/$defs/Sex",
            "description": "Sex of the individual. Value from NCIT General Qualifier `NCIT:C27993`:    * `unknown`: not assessed or not availablel `NCIT:C17998` * `female`: `NCIT:C16576` * `male`: `NCIT:C20197`"
        },
        "treatments": {
            "items": {
                "$ref": "../common/treatment.json"
            },
            "type": "array"
        }
    },
    "required": [
        "id",
        "sex"
    ],
    "title": "Individual",
    "type": "object"
}

=== ga4gh-beacon/beacon-v2/models/json/beacon-v2-default-model/individuals/examples/individual-MID-example.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "diseases": [
        {
            "ageOfOnset": {
                "ageGroup": {
                    "id": "NCIT:C49685",
                    "label": "Adult 18-65 Years Old"
                }
            },
            "diseaseCode": {
                "id": "OMIM:164400",
                "label": "Spinocerebellar ataxia 1"
            },
            "familyHistory": false,
            "severity": {
                "id": "HP:0012829",
                "label": "Profound"
            },
            "stage": {
                "id": "OGMS:0000119",
                "label": "acute onset"
            }
        }
    ],
    "ethnicity": {
        "id": "NCIT:C43851",
        "label": "European"
    },
    "geographicOrigin": {
        "id": "GAZ:00002955",
        "label": "Slovenia"
    },
    "id": "Ind001",
    "measures": [
        {
            "assayCode": {
                "id": "LOINC:26515-7",
                "label": "Platelets [#/volume] in Blood"
            },
            "date": "2017-05-03",
            "measurementValue": {
                "units": {
                    "id": "NCIT:C103452",
                    "label": "Per Milliliter"
                },
                "value": 55345
            },
            "observationMoment": {
                "age": {
                    "iso8601duration": "P55Y8M12D"
                }
            }
        }
    ],
    "sex": {
        "id": "NCIT:C16576",
        "label": "female"
    }
}
